### ISSUE TITLE
Hoarder encountered error on Heroku

### ISSUE THREAD

**Issue by Asim-Tahir** [KGBTR/Reddit-Repost-Bot#2]
```log
2021-03-16T07:07:28.471527+00:00 app[hoarder.1]: Traceback (most recent call last):
2021-03-16T07:07:28.471528+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
2021-03-16T07:07:28.471713+00:00 app[hoarder.1]:     (self._dns_host, self.port), self.timeout, **extra_kw
2021-03-16T07:07:28.471716+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
2021-03-16T07:07:28.471836+00:00 app[hoarder.1]:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2021-03-16T07:07:28.471839+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/socket.py", line 745, in getaddrinfo
2021-03-16T07:07:28.472247+00:00 app[hoarder.1]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2021-03-16T07:07:28.472248+00:00 app[hoarder.1]: socket.gaierror: [Errno -2] Name or service not known
2021-03-16T07:07:28.472248+00:00 app[hoarder.1]: 
2021-03-16T07:07:28.472249+00:00 app[hoarder.1]: During handling of the above exception, another exception occurred:
2021-03-16T07:07:28.472249+00:00 app[hoarder.1]: 
2021-03-16T07:07:28.472254+00:00 app[hoarder.1]: Traceback (most recent call last):
2021-03-16T07:07:28.472254+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
2021-03-16T07:07:28.472554+00:00 app[hoarder.1]:     chunked=chunked,
2021-03-16T07:07:28.472555+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 394, in _make_request
2021-03-16T07:07:28.472753+00:00 app[hoarder.1]:     conn.request(method, url, **httplib_request_kw)
2021-03-16T07:07:28.472754+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 234, in request
2021-03-16T07:07:28.472897+00:00 app[hoarder.1]:     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2021-03-16T07:07:28.472901+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1287, in request
2021-03-16T07:07:28.473394+00:00 app[hoarder.1]:     self._send_request(method, url, body, headers, encode_chunked)
2021-03-16T07:07:28.473395+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1333, in _send_request
2021-03-16T07:07:28.474014+00:00 app[hoarder.1]:     self.endheaders(body, encode_chunked=encode_chunked)
2021-03-16T07:07:28.474015+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1282, in endheaders
2021-03-16T07:07:28.474559+00:00 app[hoarder.1]:     self._send_output(message_body, encode_chunked=encode_chunked)
2021-03-16T07:07:28.474560+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1042, in _send_output
2021-03-16T07:07:28.475029+00:00 app[hoarder.1]:     self.send(msg)
2021-03-16T07:07:28.475030+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 980, in send
2021-03-16T07:07:28.475413+00:00 app[hoarder.1]:     self.connect()
2021-03-16T07:07:28.475414+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 200, in connect
2021-03-16T07:07:28.475543+00:00 app[hoarder.1]:     conn = self._new_conn()
2021-03-16T07:07:28.475545+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
2021-03-16T07:07:28.475687+00:00 app[hoarder.1]:     self, "Failed to establish a new connection: %s" % e
2021-03-16T07:07:28.475693+00:00 app[hoarder.1]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdaaae5d518>: Failed to establish a new connection: [Errno -2] Name or service not known
2021-03-16T07:07:28.475693+00:00 app[hoarder.1]: 
2021-03-16T07:07:28.475694+00:00 app[hoarder.1]: During handling of the above exception, another exception occurred:
2021-03-16T07:07:28.475694+00:00 app[hoarder.1]: 
2021-03-16T07:07:28.475697+00:00 app[hoarder.1]: Traceback (most recent call last):
2021-03-16T07:07:28.475710+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
2021-03-16T07:07:28.475972+00:00 app[hoarder.1]:     timeout=timeout
2021-03-16T07:07:28.475972+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
2021-03-16T07:07:28.476248+00:00 app[hoarder.1]:     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
2021-03-16T07:07:28.476251+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
2021-03-16T07:07:28.476490+00:00 app[hoarder.1]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2021-03-16T07:07:28.476511+00:00 app[hoarder.1]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='twlba5j7oo5g4kj5.onion', port=80): Max retries exceeded with url: /?img=11561136017.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdaaae5d518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2021-03-16T07:07:28.476511+00:00 app[hoarder.1]: 
2021-03-16T07:07:28.476511+00:00 app[hoarder.1]: During handling of the above exception, another exception occurred:
2021-03-16T07:07:28.476512+00:00 app[hoarder.1]: 
2021-03-16T07:07:28.476514+00:00 app[hoarder.1]: Traceback (most recent call last):
2021-03-16T07:07:28.476533+00:00 app[hoarder.1]:   File "hoarder.py", line 15, in <module>
2021-03-16T07:07:28.476641+00:00 app[hoarder.1]:     collect_hashes()
2021-03-16T07:07:28.476642+00:00 app[hoarder.1]:   File "hoarder.py", line 11, in collect_hashes
2021-03-16T07:07:28.476742+00:00 app[hoarder.1]:     hashcollector.start_collectin()
2021-03-16T07:07:28.476743+00:00 app[hoarder.1]:   File "/app/HashCollector.py", line 56, in start_collectin
2021-03-16T07:07:28.476857+00:00 app[hoarder.1]:     hashedimg = HashedImage(post.url, calculate_on_init=True)
2021-03-16T07:07:28.476858+00:00 app[hoarder.1]:   File "/app/CompareImageHashes/CompareImageHashes.py", line 13, in __init__
2021-03-16T07:07:28.476963+00:00 app[hoarder.1]:     self.opened_stream = Image.open(self._get_raw_img(pic_url))
2021-03-16T07:07:28.476964+00:00 app[hoarder.1]:   File "/app/CompareImageHashes/CompareImageHashes.py", line 36, in _get_raw_img
2021-03-16T07:07:28.477059+00:00 app[hoarder.1]:     img = requests.get(url, stream=True)
2021-03-16T07:07:28.477064+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/api.py", line 76, in get
2021-03-16T07:07:28.477189+00:00 app[hoarder.1]:     return request('get', url, params=params, **kwargs)
2021-03-16T07:07:28.477193+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/api.py", line 61, in request
2021-03-16T07:07:28.477307+00:00 app[hoarder.1]:     return session.request(method=method, url=url, **kwargs)
2021-03-16T07:07:28.477309+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
2021-03-16T07:07:28.477551+00:00 app[hoarder.1]:     resp = self.send(prep, **send_kwargs)
2021-03-16T07:07:28.477554+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
2021-03-16T07:07:28.477826+00:00 app[hoarder.1]:     r = adapter.send(request, **kwargs)
2021-03-16T07:07:28.477826+00:00 app[hoarder.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
2021-03-16T07:07:28.478064+00:00 app[hoarder.1]:     raise ConnectionError(e, request=request)
2021-03-16T07:07:28.478069+00:00 app[hoarder.1]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='twlba5j7oo5g4kj5.onion', port=80): Max retries exceeded with url: /?img=11561136017.png (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdaaae5d518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by scrubjay55** [comment]
30ac2f5de43bce418369ee9bf21a0b62f04d5efa
